theme: jekyll-theme-cayman
title: "Searena App"
description: "Searena merupakan Aplikasi Desktop yang dikembangkan menggunakan program C# dengan integrasi API Weather dan Location untuk memberikan pengalaman wisata maritim yang optimal. Dengan memanfaatkan teknologi .NET Framework, Searena menghadirkan interface yang responsif dan stabil untuk sistem operasi Windows. Fitur-fitur dalam Searena juga dirancang untuk membantu wisatawan dalam mengakses aplikasi ini dengan mudah."

